### PR TITLE
[translate to english] Build a CubeFS cluster on a single machine fix #8

### LINKED ISSUE #8: [translate to english] Build a CubeFS cluster on a single machine
I need someone to translate this article to english, thanks

https://mp.weixin.qq.com/s/_-CcKBbNBRyR6mHkfNZIdw

### LINKED ISSUE #29: [translate to english] Introduction to CubeFS quota features
I need someone to translate this article to english, thanks

https://mp.weixin.qq.com/s/bme5Jy0ThYEu6WGljAUQfw

### PR DESCRIPTION
**Pull request by hooklee2000**
fix #8 
fix #29 
Modify the cover image as needed：

/images/cover/single-node_Deployment_of_CubeFS_Cluster.png

### CODE REVIEW

**Comment by heymingwei** [comment]
the pictures also need to be translated @hooklee2000

**Comment by hooklee2000** [comment]
> the pictures also need to be translated @hooklee2000
done

**Review by heymingwei — APPROVED** [review]
LGTM

**Review by NaturalSelect — APPROVED** [review]
LGTM

**Pull request merged**
